import './toContact';
import '../scss/main.scss';
import './fontawesome';
import './barba';
import './firebase';
import './toTop';
import 'intersection-observer';
import './hamberger';
import './scroll';
import './loader';
import './copyright'
